import numpy as np

import sys

a=np.array([1,2,3,4])
a1=np.array([(1,2,3,4,5,6,7,8),(5,6,7,8,9,10,11,12)])

print("one Dimensional array",a)
print("Two dimensuinal arry",a1)
print("####################################################################################################################")
print("checking numpay is fast then list: ")
s1=range(100)
print("Sizze occupied by list:",sys.getsizeof(2)*len(s1))
s2=np.arange(100)
print("Size occupied by an numpy:",s2.size*s2.itemsize)
print("####################################################################################################################################################################################")
print("dimension of numpy:", a1.ndim)
print("Number od values in numpy:",a1.itemsize)
print("Data type of an numpy:",a1.dtype)
print("size of an numpy array:",a1.size)
print("####################################################################################################################################################################################")
print("shape of array i.e row and column:",a1.shape)
# a2=a1.reshape(4,2)
# print("reshape to colunm and row:",a2)
print("####################################################################################################################################################################################")
print("Indexing in numpy:")
print(a1)
print("get value of 1 row 3rd col:",a1[0,2])
print("all row's second index",a1[0,0:])

print("####################################################################################################################################################################################")
print("Line space i.e create random number")
a3=np.linspace(5,10,10)
print("random number between 5-10 of 10 digit:",a3)
print("max number in array:",a3.max())
print("min in array:",a3.min())
print("sum of array:",a3.sum())
print("sum of 0-axis i.e column:",a1.sum(axis=0))
print("ADDition col 3:",a1.sum(3))
print("sum of 1-axis i.e row:",a1.sum(axis=1))
print("####################################################################################################################################################################################")
print("square root of each element:",np.sqrt(a1))
print("standerd deviation :",np.std(a1))
print("conver 2d arry in one row:")
a4=a1.ravel()
print("into col formate",a4)
print("#####################################################################################################################################################################################")
print("exponential:",np.exp(a))
print("natural log:",np.log(a))
print("log base 10:",np.log10(a))
print("Power of each ele:",np.power(a,2))
print("reciprocal of each ele:",np.reciprocal(a))
print("#####################################################################################################################################################################################")
print("calculations with complex numbewr:")
c1=np.array([3+3j,6-78j,55+5j])
print("print real number:",np.real(c1))
print("imaginary part:",np.imag(c1))
print("find conjugate ie sign change",np.conjugate(c1))
